#!/usr/bin/env bash
set -euo pipefail

# ============================================================
# MBS UniWise AI - Portable Apache Reverse Proxy Installer
# ============================================================
# Default:
#   Public path : /mbs-retriever/
#   Backend     : http://127.0.0.1:8000/
#
# Optional overrides:
#   PUBLIC_PATH=/retriever/ BACKEND_URL=http://127.0.0.1:9000/ ./install_apache_proxy.sh
# ============================================================

CONF_NAME="mbs-retriever"
CONF_FILE="/etc/apache2/conf-available/${CONF_NAME}.conf"

PUBLIC_PATH="${PUBLIC_PATH:-/mbs-retriever/}"
BACKEND_URL="${BACKEND_URL:-http://127.0.0.1:8000/}"

if [[ "${EUID}" -ne 0 ]]; then
  echo "ERROR: Please run as root or with sudo."
  exit 1
fi

if ! command -v apache2ctl >/dev/null 2>&1; then
  echo "ERROR: Apache2 is not installed."
  exit 1
fi

if ! command -v a2enmod >/dev/null 2>&1 || ! command -v a2enconf >/dev/null 2>&1; then
  echo "ERROR: Debian/Ubuntu Apache helper commands were not found."
  exit 1
fi

# Normalize trailing slash
[[ "${PUBLIC_PATH}" == /* ]] || PUBLIC_PATH="/${PUBLIC_PATH}"
[[ "${PUBLIC_PATH}" == */ ]] || PUBLIC_PATH="${PUBLIC_PATH}/"
[[ "${BACKEND_URL}" == */ ]] || BACKEND_URL="${BACKEND_URL}/"

echo "== MBS Retriever Apache Proxy Installer =="
echo "Public path : ${PUBLIC_PATH}"
echo "Backend URL : ${BACKEND_URL}"
echo

# Enable required Apache modules
a2enmod proxy proxy_http headers >/dev/null

# Back up an existing config before replacing it
if [[ -f "${CONF_FILE}" ]]; then
  BACKUP="${CONF_FILE}.bak.$(date +%Y%m%d%H%M%S)"
  cp "${CONF_FILE}" "${BACKUP}"
  echo "Existing config backed up to: ${BACKUP}"
fi

cat > "${CONF_FILE}" <<EOF
# MBS UniWise AI External Retriever
# Generated by install_apache_proxy.sh

ProxyPreserveHost On

ProxyPass        ${PUBLIC_PATH} ${BACKEND_URL}
ProxyPassReverse ${PUBLIC_PATH} ${BACKEND_URL}
EOF

a2enconf "${CONF_NAME}" >/dev/null

echo "Checking Apache configuration..."
apache2ctl configtest

echo "Reloading Apache..."
systemctl reload apache2

echo
echo "Apache reverse proxy installed successfully."
echo "Public health URL:"
echo "  http://<SERVER-IP>${PUBLIC_PATH}health"
echo

# Local backend health check (best effort)
if command -v curl >/dev/null 2>&1; then
  HEALTH_URL="${BACKEND_URL}health"
  echo "Checking local Retriever health: ${HEALTH_URL}"
  if curl -fsS --max-time 10 "${HEALTH_URL}"; then
    echo
    echo "Local Retriever health check: OK"
  else
    echo
    echo "WARNING: Apache proxy was installed, but the local Retriever health check failed."
    echo "Check: systemctl status mbs-retriever --no-pager"
  fi
else
  echo "curl is not installed; skipping local health check."
fi

echo
echo "Done."
